// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBar4D8_OeHxSl_OnQ0kkU5RbFoNUiHjww',
    appId: '1:789081695498:web:c627fa7c890e85471dc6f3',
    messagingSenderId: '789081695498',
    projectId: 'expenso-01',
    authDomain: 'expenso-01.firebaseapp.com',
    storageBucket: 'expenso-01.firebasestorage.app',
    measurementId: 'G-VB7KV974R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdStzz9_V9lNPHKgBun5sFMXRojJfSnrE',
    appId: '1:789081695498:android:a4729f80c40bbfbe1dc6f3',
    messagingSenderId: '789081695498',
    projectId: 'expenso-01',
    storageBucket: 'expenso-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2RK728DgL0SUMVfxH0bUC4UXJsODKGRU',
    appId: '1:789081695498:ios:4b07afb10d5f483c1dc6f3',
    messagingSenderId: '789081695498',
    projectId: 'expenso-01',
    storageBucket: 'expenso-01.firebasestorage.app',
    iosBundleId: 'com.example.expenso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2RK728DgL0SUMVfxH0bUC4UXJsODKGRU',
    appId: '1:789081695498:ios:4b07afb10d5f483c1dc6f3',
    messagingSenderId: '789081695498',
    projectId: 'expenso-01',
    storageBucket: 'expenso-01.firebasestorage.app',
    iosBundleId: 'com.example.expenso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBar4D8_OeHxSl_OnQ0kkU5RbFoNUiHjww',
    appId: '1:789081695498:web:418129797a3bd6ee1dc6f3',
    messagingSenderId: '789081695498',
    projectId: 'expenso-01',
    authDomain: 'expenso-01.firebaseapp.com',
    storageBucket: 'expenso-01.firebasestorage.app',
    measurementId: 'G-5J2N9SY6N8',
  );
}
